# Generated by Django 6.0.2 on 2026-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_persona_alcance_autocertificacion_comunicacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
