# Generated by Django 6.0.2 on 2026-02-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('perspectiva', models.CharField(choices=[('financiera', 'Financiera'), ('cliente', 'Cliente'), ('procesos_internos', 'Procesos Internos'), ('aprendizaje_crecimiento', 'Aprendizaje y Crecimiento')], max_length=25, verbose_name='Perspectiva CMI')),
                ('indicador', models.CharField(blank=True, max_length=200, verbose_name='Indicador')),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Actual')),
                ('valor_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Objetivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('progreso', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Progreso (%)')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
    ]
