# Generated by Django 6.0.2 on 2026-02-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_changerequest_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planificación'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('on_hold', 'En Espera'), ('modified', 'Modificado')], default='planning', max_length=20, verbose_name='Estado'),
        ),
    ]
