# Generated by Django 6.0.2 on 2026-02-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Artículo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Estimado')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planned', max_length=20, verbose_name='Estado')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Adquisición',
                'verbose_name_plural': 'Adquisiciones',
            },
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_baseline', models.TextField(verbose_name='Línea Base del Alcance')),
                ('schedule_baseline', models.TextField(verbose_name='Línea Base del Cronograma')),
                ('cost_baseline', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Línea Base de Costo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Línea Base',
                'verbose_name_plural': 'Líneas Base',
            },
        ),
    ]
