# Generated by Django 6.0.2 on 2026-02-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_acquisition_baseline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Seguimiento', 'verbose_name_plural': 'Seguimientos'},
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='perspectiva',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='progreso',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='valor_actual',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='valor_objetivo',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='ac',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='AC (Actual Cost)'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cpi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='CPI (Cost Performance Index)'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='ev',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='EV (Earned Value)'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='pv',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='PV (Planned Value)'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='spi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='SPI (Schedule Performance Index)'),
        ),
    ]
