# Generated by Django 6.0.2 on 2026-02-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_seguimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaConstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.TextField(verbose_name='Alcance')),
                ('entregables', models.TextField(verbose_name='Entregables')),
                ('justificacion', models.TextField(verbose_name='Justificación')),
                ('objetivos', models.TextField(verbose_name='Objetivos')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Acta de Constitución',
                'verbose_name_plural': 'Actas de Constitución',
            },
        ),
    ]
