# Generated by Django 6.0.2 on 2026-02-23 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_activity_predecessor_milestone_enhancements'),
        ('stakeholders', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicacion',
            name='interesado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholder', verbose_name='Interesado'),
        ),
    ]
