# Generated by Django 5.2.8 on 2026-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_notification_recipient_read_tracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AlterModelOptions(
            name='cronograma',
            options={'managed': False, 'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real'),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Real'),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio Real'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cv',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='CV (Cost Variance)'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='sv',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='SV (Schedule Variance)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Planificado'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de Fin Planificada'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de Inicio Planificada'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
