# Generated by Django 5.2.8 on 2026-05-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_delete_persona_alter_cronograma_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Trimestre 1, Corte 2, Q1 2026...', max_length=100, verbose_name='Nombre del corte')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio del período')),
                ('end_date', models.DateField(verbose_name='Fecha de fin del período')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (1, 2, 3...)', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Corte del Proyecto',
                'verbose_name_plural': 'Cortes del Proyecto',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('project', 'sort_order'), name='unique_cut_order_per_project')],
            },
        ),
    ]
