# Generated by Django 6.0.2 on 2026-02-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_activity_options_alter_milestone_options_and_more'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'verbose_name': 'Riesgo', 'verbose_name_plural': 'Riesgos'},
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='identified_by',
            field=models.CharField(max_length=200, verbose_name='Identificado Por'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='identified_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Identificación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=10, verbose_name='Impacto'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigation_plan',
            field=models.TextField(blank=True, verbose_name='Plan de Mitigación'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Probabilidad'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('identified', 'Identificado'), ('mitigated', 'Mitigado'), ('occurred', 'Ocurrido')], default='identified', max_length=20, verbose_name='Estado'),
        ),
    ]
