# Generated by Django 5.2.8 on 2026-01-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.DeleteModel(
            name='DashboardConfig',
        ),
    ]
