# Generated by Django 5.2.8 on 2025-12-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionproyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('costoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoEstimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaFinProyecto', models.DateField()),
                ('fechaInicioProyecto', models.DateField()),
                ('observaciones', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionproyecto.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoPlanificado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costoReal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('esHito', models.BooleanField()),
                ('estado', models.IntegerField(choices=[(0, 'Iniciado'), (1, 'En Progreso'), (2, 'Completado'), (3, 'Cancelado')], default=0)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('fechaInicioReal', models.DateField()),
                ('fechaFinReal', models.DateField()),
                ('porcentajeCompletado', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('actividadAnterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineabase.actividad')),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineabase.cronograma')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineabase.presupuesto')),
                ('recursos', models.ManyToManyField(blank=True, to='lineabase.recurso')),
            ],
        ),
    ]
