# Generated by Django 5.2.8 on 2026-01-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionproyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('fecha', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionproyecto.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedValuePV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EarnedValueEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CostPerformanceIndexCPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.seguimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ShedulePerformanceIndexSPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.seguimiento')),
            ],
        ),
    ]
