# Generated by Django 6.0.2 on 2026-02-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('manager', 'Project Manager'), ('team_member', 'Team Member'), ('client', 'Client'), ('sponsor', 'Sponsor'), ('other', 'Other')], max_length=20)),
                ('contact_info', models.TextField(blank=True)),
                ('interest_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('power_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('projects', models.ManyToManyField(related_name='stakeholders', to='projects.project')),
            ],
        ),
    ]
