# Generated by Django 6.0.2 on 2026-02-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_activity_options_alter_milestone_options_and_more'),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'verbose_name': 'Interesado', 'verbose_name_plural': 'Interesados'},
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='Información de Contacto'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='interest_level',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=10, verbose_name='Nivel de Interés'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='power_level',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=10, verbose_name='Nivel de Poder'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='projects',
            field=models.ManyToManyField(related_name='stakeholders', to='projects.project', verbose_name='Proyectos'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=models.CharField(choices=[('manager', 'Gerente de Proyecto'), ('team_member', 'Miembro del Equipo'), ('client', 'Cliente'), ('sponsor', 'Patrocinador'), ('other', 'Otro')], max_length=20, verbose_name='Rol'),
        ),
    ]
