# Generated by Django 6.0.2 on 2026-02-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_changerequest_notification'),
        ('stakeholders', '0002_alter_stakeholder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Calificación')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholder', verbose_name='Interesado')),
            ],
            options={
                'verbose_name': 'Retroalimentación',
                'verbose_name_plural': 'Retroalimentaciones',
            },
        ),
    ]
