# Generated by Django 6.0.2 on 2026-02-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_activity_options_alter_milestone_options_and_more'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Unidad'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('human', 'Humano'), ('material', 'Material'), ('equipment', 'Equipo'), ('financial', 'Financiero'), ('other', 'Otro')], max_length=20, verbose_name='Tipo'),
        ),
    ]
