# Generated by Django 6.0.2 on 2026-02-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_seguimiento'),
        ('resources', '0002_alter_resource_options_alter_resource_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='project',
        ),
        migrations.AddField(
            model_name='resource',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.activity', verbose_name='Actividad'),
        ),
    ]
